// Config partagée entre ClubKioskPage et ClubKioskPlayersPage
export const KIOSK_TESTS = [
  {
    key: 'hooper',
    label: 'HOOPER',
    sub: 'Bien-être · Fatigue · Sommeil · Stress · Courbatures',
    color: '#9d7dea',
    bg: '#f5f0ff',
    border: '#d4c5f9',
    doneTable: 'hooper_logs',
    doneField: null,
  },
  {
    key: 'rpe',
    label: 'RPE Séance',
    sub: 'Effort perçu · Durée · Type de séance',
    color: '#ff7043',
    bg: '#fff5f2',
    border: '#ffcdb8',
    doneTable: 'rpe_logs',
    doneField: null,
  },
  {
    key: 'topset',
    label: 'Topset',
    sub: 'Force max · Exercices fondamentaux',
    color: '#1a6db5',
    bg: '#f0f7ff',
    border: '#b8d4f0',
    doneTable: 'kiosk_topset',
    doneField: null,
  },
  {
    key: 'cmj',
    label: 'CMJ',
    sub: 'Détente verticale · Hauteur en cm',
    color: '#2d6a4f',
    bg: '#e8f5ee',
    border: '#a8d5b8',
    doneTable: 'charge_logs',
    doneField: 'cmj_cm',
  },
  {
    key: 'squat_jump',
    label: 'Squat Jump',
    sub: 'Détente sans contre-mouvement · Ratio SJ/CMJ',
    color: '#1a7a5e',
    bg: '#eafaf4',
    border: '#9ad5bf',
    doneTable: 'squat_jump_logs',
    doneField: null,
  },
  {
    key: 'sprint',
    label: 'Sprint',
    sub: '10m · 30m · Split 20m',
    color: '#c0392b',
    bg: '#fdecea',
    border: '#f5c6c6',
    doneTable: 'sprint_logs',
    doneField: null,
  },
  {
    key: 'bronco',
    label: 'Bronco',
    sub: '5 × 20m · Test endurance rugby',
    color: '#6d3a1a',
    bg: '#fdf0e8',
    border: '#e8c4a0',
    doneTable: 'bronco_logs',
    doneField: null,
  },
  {
    key: 'poids',
    label: 'Poids du matin',
    sub: 'Monitoring quotidien · Kilogrammes',
    color: '#555',
    bg: '#f5f3ef',
    border: '#d8d4ce',
    doneTable: 'weight_logs',
    doneField: null,
  },
  {
    key: 'doms',
    label: 'DOMS',
    sub: 'Courbatures localisées · Zones musculaires',
    color: '#8b1a4a',
    bg: '#fdf0f5',
    border: '#e8b0c8',
    doneTable: 'doms_logs',
    doneField: null,
  },
  {
    key: 'prehension',
    label: 'Préhension',
    sub: 'Force de serrage · Kilogrammes',
    color: '#b5830a',
    bg: '#fdf6e3',
    border: '#f0d080',
    doneTable: 'charge_logs',
    doneField: 'prehension_kg',
  },
  {
    key: 'hydratation',
    label: 'Hydratation',
    sub: "Couleur urine · Indice d'hydratation",
    color: '#4d9fff',
    bg: '#eef6ff',
    border: '#a8cff5',
    doneTable: 'hydratation_logs',
    doneField: null,
  },
]
