// Config partagée entre ClubKioskPage et ClubKioskPlayersPage
export const KIOSK_TESTS = [
  {
    key: 'hooper',
    emoji: '🧠',
    label: 'HOOPER',
    sub: 'Bien-être · Fatigue · Sommeil · Stress · Courbatures',
    color: '#9d7dea',
    bg: '#f5f0ff',
    border: '#d4c5f9',
    doneTable: 'hooper_logs',
    doneField: null,
  },
  {
    key: 'rpe',
    emoji: '⚡',
    label: 'RPE Séance',
    sub: 'Effort perçu · Durée · Type de séance',
    color: '#ff7043',
    bg: '#fff5f2',
    border: '#ffcdb8',
    doneTable: 'rpe_logs',
    doneField: null,
  },
  {
    key: 'topset',
    emoji: '🏋️',
    label: 'Topset',
    sub: 'Force max · Exercices fondamentaux',
    color: '#1a6db5',
    bg: '#f0f7ff',
    border: '#b8d4f0',
    doneTable: 'kiosk_topset',
    doneField: null,
  },
  {
    key: 'cmj',
    emoji: '📏',
    label: 'CMJ',
    sub: 'Détente verticale · Hauteur en cm',
    color: '#2d6a4f',
    bg: '#e8f5ee',
    border: '#a8d5b8',
    doneTable: 'charge_logs',
    doneField: 'cmj_cm',
  },
  {
    key: 'prehension',
    emoji: '✊',
    label: 'Préhension',
    sub: 'Force de serrage · Kilogrammes',
    color: '#b5830a',
    bg: '#fdf6e3',
    border: '#f0d080',
    doneTable: 'charge_logs',
    doneField: 'prehension_kg',
  },
  {
    key: 'hydratation',
    emoji: '💧',
    label: 'Hydratation',
    sub: "Couleur urine · Indice d'hydratation",
    color: '#4d9fff',
    bg: '#eef6ff',
    border: '#a8cff5',
    doneTable: 'hydratation_logs',
    doneField: null,
  },
]
